export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET'

export const ORDER_LISTS_REQUEST = 'ORDER_LISTS_REQUEST'
export const ORDER_LISTS_SUCCESS = 'ORDER_LISTS_SUCCESS'
export const ORDER_LISTS_FAIL = 'ORDER_LISTS_FAIL'
export const ORDER_LISTS_RESET = 'ORDER_LISTS_RESET'